{% set name = "mrmr_selection" %}
{% set version = "0.2.8" %}
{% set commit = "3ea01aac88628b678aa88f734524594b0edd63d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # no sdist provided, no tags on github
  # see issue: https://github.com/smazzanti/mrmr/issues/45
  url: https://github.com/smazzanti/mrmr/archive/{{ commit }}.tar.gz
  sha256: 78a97f829f0dc1bdf05049458964ef56f05be0d16c2dc942a1720b94439c9641

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - category_encoders
    - jinja2
    - tqdm
    - joblib
    - pandas >=1.0.3
    - numpy >=1.18.1
    - scikit-learn
    - scipy
    - polars >=0.12.5
  run:
    - python >=3.7
    - category_encoders
    - jinja2
    - tqdm
    - joblib
    - pandas >=1.0.3
    - numpy >=1.18.1
    - scikit-learn
    - scipy
    - polars >=0.12.5

test:
  imports:
    - mrmr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smazzanti/mrmr
  summary: mRMR (minimum-Redundancy-Maximum-Relevance) for automatic feature selection at scale.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
